### ISSUE TITLE
如何处理本地图片上传？

### ISSUE THREAD

**Issue by yibie** [Eliot00/mp-org#19]
如题。

不太理解 README 中对 uploader 的解释

**Comment by Eliot00** [comment]
当你的文档中存在：

```orgmode
[[./image.png]]
```

并且配置了：

```toml
[image]
uploader = "oss-uploader"
```

点击上传图片就会调用`oss-uploader ./image.png`
